@startuml classes
set namespaceSeparator none
class "AgentManager" as classes.agent_manager.AgentManager {
  executor
  initialize(settings, tools)
}
class "InterfaceManager" as classes.interface_manager.InterfaceManager {
  initialize(settings: Settings, agent_manager) -> None
}
class "RagTool" as classes.rag_tool.RagTool {
  rag_tool
}
class "Settings" as classes.settings.Settings {
  agent_model : ChatDeepSeek
  agent_prompt_template : str
  embedder : OllamaEmbeddings
  params : dict
  rag_model : ChatDeepSeek
  retriever_params : dict
  tools : list
  vectorizing_params : dict
}
class "ToolManager" as classes.tool_manager.ToolManager {
  tools
  initialize(settings: Settings, vectorstore_manager)
}
class "VectorstoreManager" as classes.vectorstore_manager.VectorstoreManager {
  vectorstore
  get_retriever(settings, retriever_filter: dict) -> VectorStoreRetriever
  initialize(settings: Settings)
}
classes.settings.Settings --o classes.vectorstore_manager.VectorstoreManager : _settings
@enduml
