[theme]
primaryColor = "DarkOrange"
backgroundColor = "DarkCyan"
secondaryBackgroundColor = "Snow"
codeBackgroundColor = "DarkSlateGray"
textColor = "SteelBlue"
linkColor = "#764ba2"
baseRadius = "10px"
showWidgetBorder = false
font = "monospace"
baseFontSize=15
[theme.sidebar]
primaryColor = "MediumTurquoise"
backgroundColor = "CadetBlue"
textColor = "Ivory"
baseRadius = "7px"
font = "sans-serif"




#st.markdown("""
#                <style>
#                .main-header {
#                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
#                    padding: 2rem 0;
#                    border-radius: 15px;
#                    margin-bottom: 2rem;
#                    text-align: center;
#                    color: white;
#                    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
#                }
#                .main-header h1 {
#                    font-size: 2.5rem;
#                    margin-bottom: 0.5rem;
#                    font-weight: 700;
#                }
#                .main-header p {
#                    font-size: 1.1rem;
#                    opacity: 0.9;
#                    margin: 0;
#                }
#                .stChatMessage {
#                    position: relative
#                    display: flex;
#                    align-items: flex-start !important;
#                    border-radius: 10px;
#                    border-left: 2px solid #667eea;
#                    border-bottom: 2px solid #667eea;
#                    border-right: 2px solid #764ba2;
#                    border-top: 2px solid #764ba2;
#                }
#                div[data-testid="stChatMessage"] p {
#                    font-weight: bold;
#                    color: #667eea;
#                    font-family: 'Courier New', Courier, monospace !important;
#                    font-size: 16;
#                    min-height: 2rem;
#                    margin: 0;
#                }
#                .debug-message {
#                    background-color: #fff3cd;
#                    color: #856404;
#                    padding: 10px;
#                    border-radius: 5px;
#                    border: 1px solid #ffeeba;
#                    font-family: monospace;
#                    margin-bottom: 10px;
#                }
#                h3, h2, h1, strong {
#                    font-weight: bold;
#                    color: #667eea;
#                    font-family: 'Courier New', Courier, monospace !important;
#                }
#                li {
#                    font-weight: bold;
#                    color: #667eea;
#                    font-family: 'Courier New', Courier, monospace !important;
#                    font-style: italic;
#                }
#                .stExpander {
#                    font-weight: bold;
#                    color: #856404;
#                    background-color: #fff3cd;
#                    padding: 8px;
#                    border-radius: 5px;
#                }
#                .stExpanderDetail {
#                    background-color: #fffbea;
#                    padding: 10px;
#                    border: 1px solid #ffeeba;
#                    border-radius: 5px;
#                }
#                </style>
#            """, unsafe_allow_html=True)